"""
Global configuration for the ISIC Rev.5 semantic classification pipeline.

This module centralizes:
- File paths (database, downloads folder, ISIC JSON)
- Embedding model configuration
- Chunking and text-length thresholds
- QDA and primary qualitative data file extensions

Keeping configuration in a dedicated module ensures the pipeline remains
clean, maintainable, and easy to adapt for new datasets or environments.
"""

# ---------------------------------------------------------------------------
# File Paths (update these as needed)
# ---------------------------------------------------------------------------
"""
Path configuration for the classification pipeline.

DB_FILE:
    SQLite database generated by the data_acquisition step.
    Contains project metadata, file metadata, and download status.

DOWNLOAD_FOLDER:
    Folder created by data_acquisition containing all downloaded files.
    Structure: downloads/<repository>/<project>/<files>

ISIC_JSON_PATH:
    ISIC Rev.5 division metadata stored inside the data_classification folder.
"""
DB_FILE = r"23173040-sq26.db"
DOWNLOAD_FOLDER = r"downloads"
ISIC_JSON_PATH = r"isic_divisions.json"
 
# ---------------------------------------------------------------------------
# Embedding Model Configuration
# ---------------------------------------------------------------------------
EMBED_MODEL_NAME = "intfloat/multilingual-e5-large"
# Minimum text length required before embedding
MIN_TEXT_LENGTH = 50
# Approximate chunk size in tokens (word count proxy)
CHUNK_SIZE_TOKENS = 512
# Number of top ISIC candidates to return
TOP_K_CANDIDATES = 5

# ---------------------------------------------------------------------------
# QDA Software File Extensions (REFI-QDA, NVivo, ATLAS.ti, MaxQDA, etc.)
# ---------------------------------------------------------------------------
QDA_EXTS = {
    "qdpx", "qdc",            # REFI-QDA standard
    "nvp", "nvpx",            # NVivo
    "atlproj", "hpr7",        # ATLAS.ti, HyperRESEARCH
    "mx20", "mx22", "mx24",   # MaxQDA versions
    "ppj", "pprj", "qlt",     # QDA Miner
    "f4p", "qpd",             # f4analyse, Quirkos
}

# ---------------------------------------------------------------------------
# Primary Qualitative Data File Extensions
# ---------------------------------------------------------------------------
PRIMARY_EXTS = {
    "pdf", "txt", "docx", "doc", "rtf", "odt",     # text documents
    "csv", "tsv", "xlsx", "xls", "ods",            # structured data
}
