"""
Project type assignment module for qualitative research archives.

This module assigns each project to one of four categories based on the
file extensions present in the project:

    - QDA_PROJECT      → Contains at least one QDA software file
    - QD_PROJECT       → Contains primary qualitative data files
    - OTHER_PROJECT    → Contains files, but none are QDA or primary data
    - NOT_A_PROJECT    → Contains no usable files (all failed or unknown)

The classification is written directly into the SQLite database and is
used as a priority ordering step in the ISIC Rev.5 semantic classification
pipeline (QDA projects are processed first).
"""

import sqlite3
from collections import defaultdict

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
"""
DB_FILE:
    SQLite database generated by the data_acquisition step.
    Contains project metadata, file metadata, and download status.
    """
DB_PATH = "23173040-sq26.db"   # Update this path as needed

# QDA software file extensions (REFI-QDA, NVivo, ATLAS.ti, MaxQDA, etc.)
QDA_EXTS = {
    # REFI-QDA standard
    'qdpx', 'qdc',

    # MaxQDA formats (multiple versions)
    'mqda', 'mqbac', 'mqtc', 'mqex', 'mqmtr',
    'mx24', 'mex24', 'mc24',
    'mx22', 'mex22',
    'mx20',
    'mx18',
    'mx12',
    'mx11',
    'mx5',
    'mx4',
    'mx3',
    'mx2',
    'm2k',
    'mtr', 'mod', 'loa', 'sea',

    # NVivo
    'nvp', 'nvpx',

    # ATLAS.ti
    'atlasproj', 'atlproj', 'atlproj9',

    # QDA Miner
    'ppj', 'pprj', 'qlt',

    # f4analyse
    'f4p', 'pxp', 'bfc',

    # Quirkos
    'qpd',

    # HyperRESEARCH
    'hpr7',

    # RQDA
    'rwd',
}

# Primary qualitative data file extensions
PRIMARY_EXTS = {
    'pdf', 'txt', 'docx', 'doc', 'rtf', 'odt',     # text documents
    'mp3', 'mp4', 'mkv', 'mxf',                    # audio/video
    'csv', 'tsv', 'xlsx', 'xls', 'ods', 'xlsm',    # structured data
    'jsonl', 'xml', 'html',                        # data formats
    'md', 'rmd', 'ipynb',                          # notebooks/markdown
    'tab',                                         # tab-delimited
}

# ---------------------------------------------------------------------------
# Main Assignment Logic
# ---------------------------------------------------------------------------
def assign_project_types(db_path: str) -> None:
    """
    Assigns PROJECT_TYPE labels to all projects in the database.

    PROJECT_TYPE priority waterfall:
        1. QDA_PROJECT      → contains at least one QDA file
        2. QD_PROJECT       → contains primary qualitative data
        3. OTHER_PROJECT    → contains files but none are QDA or primary
        4. NOT_A_PROJECT    → contains no usable files

    Parameters
    ----------
    db_path : str
        Path to the SQLite database.
    """
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    # Ensure 'type' column exists
    cur.execute("PRAGMA table_info(projects)")
    existing_cols = [row[1] for row in cur.fetchall()]

    if 'type' not in existing_cols:
        cur.execute("ALTER TABLE projects ADD COLUMN type TEXT")
        print("Added 'type' column to projects table.")
    else:
        print("'type' column already exists — values will be overwritten.")

    # Build mapping: project_id → set of file extensions
    cur.execute("SELECT project_id, file_type FROM files")
    project_files: dict[int, set[str]] = defaultdict(set)

    for project_id, file_type in cur.fetchall():
        if file_type:
            project_files[project_id].add(file_type.lower())

    # Fetch all project IDs
    cur.execute("SELECT id FROM projects")
    all_project_ids = [row[0] for row in cur.fetchall()]

    counts: dict[str, int] = defaultdict(int)

    # Assign project types
    for pid in all_project_ids:
        ftypes = project_files.get(pid, set())

        if ftypes & QDA_EXTS:
            project_type = 'QDA_PROJECT'

        elif ftypes & PRIMARY_EXTS:
            project_type = 'QD_PROJECT'

        elif ftypes - {'unknown'}:
            project_type = 'OTHER_PROJECT'

        else:
            project_type = 'NOT_A_PROJECT'

        cur.execute("UPDATE projects SET type = ? WHERE id = ?", (project_type, pid))
        counts[project_type] += 1

    conn.commit()

    # Summary
    print("\n=== PROJECT_TYPE Assignment Complete ===")
    for ptype in ['QDA_PROJECT', 'QD_PROJECT', 'OTHER_PROJECT', 'NOT_A_PROJECT']:
        print(f"  {ptype}: {counts.get(ptype, 0)}")
    print(f"  TOTAL: {sum(counts.values())}")

    # Breakdown by repository
    print("\n=== Breakdown by Repository ===")
    cur.execute("""
        SELECT repository_id, type, COUNT(*)
        FROM projects
        GROUP BY repository_id, type
        ORDER BY repository_id, type
    """)
    for repo_id, ptype, count in cur.fetchall():
        print(f"  Repo {repo_id} | {ptype}: {count}")

    # Sample projects per type
    print("\n=== Sample Projects per Type ===")
    for ptype in ['QDA_PROJECT', 'QD_PROJECT', 'OTHER_PROJECT', 'NOT_A_PROJECT']:
        cur.execute(
            "SELECT id, title FROM projects WHERE type = ? LIMIT 3",
            (ptype,)
        )
        rows = cur.fetchall()
        if rows:
            print(f"\n{ptype}:")
            for pid, title in rows:
                print(f"  [{pid}] {title[:90]}")

    conn.close()
    print("\nDone. DB updated successfully.")

# ---------------------------------------------------------------------------
# Script Entry Point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    assign_project_types(DB_PATH)
